.TH hypermaze 6
.SH NAME
hypermaze \- a 3D maze like puzzle where you have to get a "string" through a "maze".
.SH SYNOPSIS
.B steam
[
.BI - options
]
.SH DESCRIPTION
.B hypermaze
is a 3D maze like puzzle where you have to get a "string" through a "maze".
For more explanations run the puzzle or for information about hypermazes in general 
see http://www.astrolog.org/labyrnth/hypermaz.htm
.SH OPTIONS
This program currently has no documented commandline options.
.SH AUTHOR
This puzzle game is developed by staircase <staircase@darkfieldgames.com>

